### ISSUE TITLE
Harvesting from DEA ows server doesn't return all catalogue

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#102]
ws endpoint: https://ows.dea.ga.gov.au

from older version of terria

![image](https://user-images.githubusercontent.com/18452161/122306735-5c6c5600-cf4c-11eb-8a8e-2a290fa4233a.png)

v8
![image](https://user-images.githubusercontent.com/18452161/122306758-64c49100-cf4c-11eb-8491-e707e7a22b24.png)

**Comment by AnaBelgun** [comment]
@nf-s I think you already fixed this?

**Comment by nf-s** [comment]
There is still a difference 

![image](https://user-images.githubusercontent.com/6187649/124218076-d3087680-db3c-11eb-8803-025b09773bb0.png)

I will investigate

**Comment by nf-s** [comment]
This is due to how TerriaJS generated catalog member IDs in `WebMapServiceCatalogGroup`. There are two WMS Layers with identical `Title` properties

![image](https://user-images.githubusercontent.com/6187649/124464722-e4b97a80-ddd7-11eb-9a15-3e99639cf3c0.png)

This is valid from a WMS perspective - so I have made a PR to change ID generation to use `Name` property if it exists

**Comment by nf-s** [comment]
PR here

**Comment by nf-s** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/5613
