### ISSUE TITLE
Onboarding UI changes - designs

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#39]
- onboarding designs based on discussions with DE Australia team

[Notes live here](https://docs.google.com/document/d/1cENE8rKUDknTd5EY9NzplAghaV4FetJij-UwIgX2AtU/edit?folder=17hIu2s1LGi2semARtA6h79yBsls3HtxM)

**Comment by vicborgy** [comment]
Here is the work ive been doing for on-boarding work:
https://projects.invisionapp.com/share/T8VM2ZBZ6C7#/screens/401335921
We felt the first step to fixing the on-boarding experience was leaning up the UI so its a little easier to understand, especially for first time users. I tried not to go too far with my designs and so more of a clean up. This is by no mens perfect or the ideal layout but I feel it is an improvement. Please note that when I do the actual on-boarding screens such as modal disclaimer & help, the layout may need to some tweaks.

**Comment by vicborgy** [comment]
Here are the designs so far - https://invis.io/VQWC0P9FC3D

Things to consider when looking at the designs
- Welcome message - I’ve focused new designs on what people see when they load Terria for the first time, making it more about us wanting to help them. So, there is room for discussion about what links we show. It should really offer support from the get go and not just a brief intro
- I’ve used the same help menu used for NSW DT (it was actually the other way round in that I leveraged the help from onboarding work for DT)
- Take the tour has not been finalised but I do see the value in doing something like this. In order to get this over the line we need to make some decisions on the what we give them help with and then work on content for this.
- I’ve provided some of my design WIP layouts at the end from pages 12-20. Just some variations on how we could use a blur effect for a different experience (but this might be best saved for later) 
- Ive also tried not to give you all too much new UI work to do so im not trying to create too many new UI elements

**Comment by vicborgy** [comment]
Here are the designs ive been working on - https://invis.io/VQWC0P9FC3D

Things to consider when looking at the designs
- Welcome message - I’ve focused new designs on what people see when they load Terria for the first time, making it more about us wanting to help them. So, there is room for discussion about what links we show. It should really offer support from the get go and not just a brief intro
- I’ve used the same help menu used for NSW DT (it was actually the other way round in that I leveraged the help from onboarding work for DT)
- Take the tour has not been finalised but I do see the value in doing something like this. In order to get this over the line we need to make some decisions on the what we give them help with and then work on content for this.
- I’ve provided some of my design WIP layouts at the end from pages 12-20. Just some variations on how we could use a blur effect for a different experience (but this might be best saved for later) 
- Ive also tried not to give you all too much new UI work to do so im not trying to create too many new UI elements

**Comment by AnaBelgun** [comment]
to demo and discuss with the team during sprint planning on 16 March

**Comment by vicborgy** [comment]
Onboarding is ready to go. https://invis.io/VQWC0P9FC3D
We still need to finalise the text content for the 'take the tour', but the shell is there ready begin.

**Comment by soyarsauce** [comment]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/9134432/77381880-11a87080-6dd3-11ea-9eed-fc3cf9452e16.png">

Just adding this before I forget, noting this really restricts us for logo usage, I would prefer the flexibility for strictly light or strictly dark background on this (so that we can maintain the light background for apps, and then individual map owners can decide if they want the dark background which means, subsequently having to update any logos to use light versions)

**Comment by soyarsauce** [comment]
(FYI @vicborgy - can you comment on above? thanks 🙂 )

**Comment by vicborgy** [comment]
Sorry @soyarsauce, should definitely be  strictly a dark backgroundA consistent dark background is the best solution. Thanks

**Comment by soyarsauce** [comment]
Any way we can keep an option for light? It would mean having to chase every single map that we roll for new logos lest we end up with this:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/9134432/77725720-4d993b00-704a-11ea-9781-ab7b44a72aa2.png">

**Comment by vicborgy** [comment]
Right ok so suggesting to have dark or light and nowhere in between as opposed to only light or only dark, right? And are you talking about the logo area only or the whole workbench?

**Comment by soyarsauce** [comment]
Yeah I mean for the option to have light or dark, and just the logo area like it currently is. So I'm saying,
- Dark mode would be like how your design is, rest of workbench matches the "dark workbench background"
- Light mode to be the current white bg when a map's logos don't have light versions readily available

**Comment by vicborgy** [comment]
Ok no worries. Light logo area should only be like NSW DT though. We want to make sure they don't push for a white workbench.

**Comment by AnaBelgun** [comment]
designs have been finalised. Any subsequent designs / refinements during development phase will be submitted as separate tickets.
