### ISSUE TITLE
DE Australia - Waterbodies - hide CSV rows

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/de-australia-map#71]
Enable the option for featureinfo to skip rows when opening csvs, so that we can include metadata at the start of each timeseries csv file.

**Comment by KeyboardSounds** [comment]
Is there an example of what one of these CSV files looks like? I can guess, but the implementation specifics depend on whether the CSV can still be parsed as a CSV with the metadata in it.

To skip rows, we have to know where the rows are in the file. Until we do that, it's just a blob of text. So we have to parse the CSV to find the rows, remove them, and then parse the CSV again. This second parse step is necessary because if we want the result to be organised according to the header row, every row has to conform to the header.

**Comment by AnaBelgun** [comment]
Pending understanding requirements - meeting to set up during week of 1 Feb 2021

**Comment by KeyboardSounds** [comment]
Met with Waterbodies folks, and the plan is that they'll add a # in front of rows that should be skipped, rather than providing the indices of those rows. This is a more flexible way of implementing it, because then if the number of rows of metadata changes, the catalog item doesn't need to be reconfigured.
